/**
 * Seed script — creates all 77 powerup cards (30 original + 47 expansion).
 * Run with: npx tsx scripts/seed-powerups.ts
 *
 * Idempotent: uses upsert on slug.
 */
import 'dotenv/config'
import { Prisma, PrismaClient } from '../src/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

type PowerupSeed = {
  slug: string
  name: string
  type: 'BOOST' | 'ATTACK'
  description: string
  effect: {
    scoring: {
      mode: 'auto' | 'manual' | 'behavioral' | 'variable'
      modifier: number | null
      conditionalKey: string | null
    }
    duration: number
    requiresTarget: boolean
    input: {
      type: 'none' | 'player_select' | 'club_select' | 'number_input' | 'hole_select'
      label: string | null
      count: number | null
    } | null
    restrictions: {
      excludePar3: boolean
    }
    flavorText: string
  }
}

const POWERUPS: PowerupSeed[] = [
  // ─── BOOST CARDS (18) ──────────────────────────────────────────────────────

  {
    slug: 'shots-for-shots',
    name: 'Shots for Shots',
    type: 'BOOST',
    description: 'Take a shot (drink), subtract that many strokes from your hole score.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'drink_count' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'How many shots (drinks) did you take?', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Liquid courage has its rewards.',
    },
  },
  {
    slug: 'walk-it-in',
    name: 'Walk it in',
    type: 'BOOST',
    description: 'Pick up your ball, take up to 10 steps toward the hole, and drop it from knee height. Play from where it lands.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "Why putt when you can walk?",
    },
  },
  {
    slug: 'left-on-red',
    name: 'Left on Red',
    type: 'BOOST',
    description: 'Tee off from the front tees on a hole of your choice.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Sometimes the shortcut is the best route.',
    },
  },
  {
    slug: 'concede',
    name: 'Concede!',
    type: 'BOOST',
    description: 'If you hit a green in regulation, your score is automatically a one-putt birdie.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'gir_check' },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "That's good. Pick it up.",
    },
  },
  {
    slug: 'can-i-get-your-number',
    name: "Can I Get Your Number?",
    type: 'BOOST',
    description: 'Ask the cart girl (or a random bystander) to pick a number 1–10. That becomes your hole score.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'random_number' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'What number did they pick? (1-10)', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Fate decides your score.",
    },
  },
  {
    slug: 'the-sandman',
    name: 'The Sandman',
    type: 'BOOST',
    description: 'Use your driver in a bunker (up to 4 attempts to escape). If you succeed, subtract 4 from your hole score.',
    effect: {
      scoring: { mode: 'auto', modifier: -4, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "Enter Sandman.",
    },
  },
  {
    slug: 'iron-man',
    name: 'Iron Man',
    type: 'BOOST',
    description: 'Use only irons for the entire hole. Subtract 2 from your score. Cannot be used on par 3s.',
    effect: {
      scoring: { mode: 'auto', modifier: -2, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: true },
      flavorText: "Real golfers don't need woods.",
    },
  },
  {
    slug: 'king-of-the-hill',
    name: 'King of the Hill',
    type: 'BOOST',
    description: 'Select up to 3 playing partners. For each consecutive hole you win outright against all of them, gain -1 to your total score. Streak ends when any partner ties or beats you.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'consecutive_wins' },
      duration: -1,
      requiresTarget: false,
      input: { type: 'player_select', label: 'Select up to 3 playing partners to compete against', count: 3 },
      restrictions: { excludePar3: false },
      flavorText: "Stay on top or fall off.",
    },
  },
  {
    slug: 'best-buddies',
    name: 'Best Buddies',
    type: 'BOOST',
    description: 'Choose a partner. You both play the hole and take the best ball between you.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'best_ball' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'player_select', label: 'Select your partner', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Teamwork makes the dream work.",
    },
  },
  {
    slug: 'the-long-drive',
    name: 'The Long Drive',
    type: 'BOOST',
    description: 'If you outdrive a chosen partner off the tee, drop your ball 10 yards past theirs.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: { type: 'player_select', label: 'Select partner to outdrive', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Grip it and rip it.",
    },
  },
  {
    slug: 'bunker-buster',
    name: 'Bunker Buster',
    type: 'BOOST',
    description: 'Each bunker you intentionally enter on this hole subtracts 1 from your score.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'bunkers_entered' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'How many bunkers did you enter?', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Sand is your friend today.",
    },
  },
  {
    slug: '1-vs-all',
    name: '1 vs ALL',
    type: 'BOOST',
    description: 'Challenge all partners on one hole. If you beat everyone outright, subtract 2 from your score. If you lose, every other player gets -1.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'beat_all_check' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Did you beat all partners? (Enter -2 if won, 0 if lost)', count: null },
      restrictions: { excludePar3: false },
      flavorText: "One against the world.",
    },
  },
  {
    slug: 'drive-for-show-putt-for-dough',
    name: 'Drive for Show, Putt for Dough',
    type: 'BOOST',
    description: 'Skip either your driver or putter for the entire hole. Subtract 1 from your score.',
    effect: {
      scoring: { mode: 'auto', modifier: -1, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "Choose your weapon — or lack thereof.",
    },
  },
  {
    slug: 'the-fluffer',
    name: 'The Fluffer',
    type: 'BOOST',
    description: 'Unlimited lie fluffing or tee-ups anywhere on the hole (including fairway and rough).',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "Every lie is a perfect lie.",
    },
  },
  {
    slug: 'skipping-stones',
    name: 'Skipping Stones',
    type: 'BOOST',
    description: 'If your ball enters a water hazard, drop on the other side with no penalty stroke.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "Water? What water?",
    },
  },
  {
    slug: 'fairway-finder',
    name: 'Fairway Finder',
    type: 'BOOST',
    description: 'Declare how many consecutive fairways you will hit. If you reach your target (par 3s excluded), subtract that number from your gross score. Miss one and the challenge fails.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'consecutive_fairways' },
      duration: -1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'How many consecutive fairways will you hit? (excluding par 3s)', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Keep it in the short grass.",
    },
  },
  {
    slug: 'playing-with-yourself',
    name: 'Playing with Yourself',
    type: 'BOOST',
    description: 'Play the hole twice and take the better score (best ball with yourself).',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'best_of_two' },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "Two tries are better than one.",
    },
  },
  {
    slug: 'happy-gilmore',
    name: 'Happy Gilmore',
    type: 'BOOST',
    description: 'Attempt an unconventional swing (running start, one-handed, etc.) on your tee shot. If you use it, subtract 1.',
    effect: {
      scoring: { mode: 'auto', modifier: -1, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: "It's all in the hips.",
    },
  },

  // ─── ATTACK CARDS (12) ─────────────────────────────────────────────────────

  {
    slug: 'just-the-tip',
    name: 'Just the Tip',
    type: 'ATTACK',
    description: 'Force an opponent to play from the championship (back) tees on this hole.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to attack', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Hope you brought your big boy clubs.",
    },
  },
  {
    slug: 'club-roulette',
    name: 'Club Roulette',
    type: 'ATTACK',
    description: "Choose a club your opponent must use for their next shot. They can't switch.",
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'club_select', label: 'Select club for opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Hope you like your 60-degree on a par 5.",
    },
  },
  {
    slug: 'drink-up',
    name: 'Drink Up!',
    type: 'ATTACK',
    description: 'Opponent must finish their drink before reaching the green. If they fail, add 2 to their score.',
    effect: {
      scoring: { mode: 'manual', modifier: 2, conditionalKey: 'drink_failed' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to attack', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Bottoms up, buttercup.",
    },
  },
  {
    slug: 'parent-trap',
    name: 'Parent Trap',
    type: 'ATTACK',
    description: 'After the hole is complete, swap your score with the chosen opponent.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'score_swap' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to swap scores with', count: null },
      restrictions: { excludePar3: false },
      flavorText: "What's yours is mine.",
    },
  },
  {
    slug: 'the-fairway-is-lava',
    name: 'The Fairway is Lava',
    type: 'ATTACK',
    description: "Each time your opponent's ball touches the fairway, add 1 to their score.",
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'fairway_touches' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to attack', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Stay off the short grass!",
    },
  },
  {
    slug: 'proximity-mine',
    name: 'Proximity Mine',
    type: 'ATTACK',
    description: 'Pick 3 future holes. If your opponent lands within 2 club lengths of a bunker on any of them, add 1 per occurrence.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'proximity_trigger' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'hole_select', label: 'Select 3 future holes to mine', count: 3 },
      restrictions: { excludePar3: false },
      flavorText: "Watch your step.",
    },
  },
  {
    slug: 'the-long-and-winding-road',
    name: 'The Long and Winding Road',
    type: 'ATTACK',
    description: "Your opponent's ball must visit both the left AND right rough before reaching the green. If they fail, add 2 to their score.",
    effect: {
      scoring: { mode: 'manual', modifier: 2, conditionalKey: 'rough_visit_failed' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to attack', count: null },
      restrictions: { excludePar3: false },
      flavorText: "The scenic route is mandatory.",
    },
  },
  {
    slug: 'go-for-glory',
    name: 'Go for Glory',
    type: 'ATTACK',
    description: "Once your opponent's ball is on the green, move it to any other spot on the green.",
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to attack', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Nice putt... from over there.",
    },
  },
  {
    slug: 'beach-boys',
    name: 'Beach Boys',
    type: 'ATTACK',
    description: 'When your ball lands in a bunker, move your opponent\'s ball into the same bunker as a reaction.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to drag into the bunker', count: null },
      restrictions: { excludePar3: false },
      flavorText: "If I'm going down, you're coming with me.",
    },
  },
  {
    slug: 'freaky-friday',
    name: 'Freaky Friday',
    type: 'ATTACK',
    description: 'Swap ball locations with an opponent at any point during the hole. Both continue with the same shot count.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to swap ball positions with', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Walk a mile in their shoes... or play from their lie.",
    },
  },
  {
    slug: 'the-texas-wedge',
    name: 'The Texas Wedge',
    type: 'ATTACK',
    description: 'If your opponent is within 50 yards of the green, they must use only their putter until the ball is in the hole.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to attack', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Putter from 50 yards? Good luck.",
    },
  },
  {
    slug: 'worst-ball',
    name: 'Worst Ball',
    type: 'ATTACK',
    description: 'Your opponent must play worst-ball with themselves for the entire hole (hit two balls, play the worse one each time).',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent to attack', count: null },
      restrictions: { excludePar3: false },
      flavorText: "Double the balls, double the pain.",
    },
  },
// --- NEW BOOST CARDS (32) ---

  {
    slug: 'stinger',
    name: 'Stinger',
    type: 'BOOST',
    description: 'Hit a knockdown shot off the tee — follow-through must stay below your shoulders. Subtract 1. If you fail, no payoff.',
    effect: {
      scoring: { mode: 'auto', modifier: -1, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Low and slow.',
    },
  },
  {
    slug: 'lefty-loosey',
    name: 'Lefty Loosey',
    type: 'BOOST',
    description: 'Play one full shot opposite-handed this hole. Subtract 1. Can be activated at any time.',
    effect: {
      scoring: { mode: 'auto', modifier: -1, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Switch hitter.',
    },
  },
  {
    slug: 'mulligan',
    name: 'Mulligan',
    type: 'BOOST',
    description: 'Re-tee any shot of your choosing on this hole, no penalty. Subtract 1.',
    effect: {
      scoring: { mode: 'auto', modifier: -1, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Do-overs are free today.',
    },
  },
  {
    slug: 'foot-wedge',
    name: 'Foot Wedge',
    type: 'BOOST',
    description: 'For 9 holes, you can move every shot one club length from its original position, no closer to the hole.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'foot_wedge_window' },
      duration: -1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Best wedge in the bag.',
    },
  },
  {
    slug: 'tee-it-high',
    name: 'Tee It High',
    type: 'BOOST',
    description: 'Use a 4+ inch tee for your tee shot. Subtract 1.',
    effect: {
      scoring: { mode: 'auto', modifier: -1, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Reach for the sky.',
    },
  },
  {
    slug: 'the-comeback',
    name: 'The Comeback',
    type: 'BOOST',
    description: 'What ever you scored on the previous hole? If you better that score your next hole, -1 to the total.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'improved_previous_score' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Improved on previous hole? Enter -1 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Bounce back stronger.',
    },
  },
  {
    slug: 'up-and-down-artist',
    name: 'Up & Down Artist',
    type: 'BOOST',
    description: 'If you get up-and-down from off the green (chip + putt), subtract 3.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'up_and_down' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Up-and-down? Enter -3 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Short game wizardry.',
    },
  },
  {
    slug: 'sand-save',
    name: 'Sand Save',
    type: 'BOOST',
    description: 'If you save par from a bunker, subtract 3.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'sand_save' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Sand save for par? Enter -3 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Beach to par.',
    },
  },
  {
    slug: 'the-tin-cup',
    name: 'The Tin Cup',
    type: 'BOOST',
    description: 'Play the entire hole using only your 7-iron (including putts). If you score par or better, subtract 3.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'tin_cup_par' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Tin Cup at par or better? Enter -3 if yes, 0 if no', count: null },
      restrictions: { excludePar3: true },
      flavorText: 'Roy McAvoy approves.',
    },
  },
  {
    slug: 'pin-seeker',
    name: 'Pin Seeker',
    type: 'BOOST',
    description: 'If your tee shot lands within 10 feet of the pin from any spot >40 yards from the hole, subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'pin_proximity' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Within 10 feet from tee? Enter -2 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Dart thrower.',
    },
  },
  {
    slug: 'long-bomb',
    name: 'Long Bomb',
    type: 'BOOST',
    description: 'If your tee shot finishes in the fairway and travels 250+ yards, subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'long_drive_fairway' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Fairway hit at 250+ yards? Enter -2 if yes, 0 if no', count: null },
      restrictions: { excludePar3: true },
      flavorText: 'Bombs away.',
    },
  },
  {
    slug: 'greenside-magic',
    name: 'Greenside Magic',
    type: 'BOOST',
    description: 'If your first chip from off the green finishes within 3 feet, subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'chip_proximity' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Chip within 3 feet? Enter -2 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Touch of a surgeon.',
    },
  },
  {
    slug: 'one-putt-wonder',
    name: 'One-Putt Wonder',
    type: 'BOOST',
    description: '9-hole window. Each hole you one-putt, subtract 1 from your total score.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'one_putt_streak' },
      duration: -1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Drains for days.',
    },
  },
  {
    slug: 'the-closer',
    name: 'The Closer',
    type: 'BOOST',
    description: 'If you sink a putt of 10 feet or longer, subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'long_putt' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: '10ft+ putt made? Enter -2 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Money under pressure.',
    },
  },
  {
    slug: 'albatross-aim',
    name: 'Albatross Aim',
    type: 'BOOST',
    description: 'Activate this card after your drive on a par 5. If you reach the green in 2 shots, subtract 3.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'par5_in_two' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'On in 2 on a par 5? Enter -3 if yes, 0 if no', count: null },
      restrictions: { excludePar3: true },
      flavorText: 'Going for it.',
    },
  },
  {
    slug: 'chip-in-bonus',
    name: 'Chip-In Bonus',
    type: 'BOOST',
    description: 'If you chip in from off the green, subtract an additional 3. Can be activated afte the chip in.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'chip_in' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Chip-in? Enter -3 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'From off the dance floor.',
    },
  },
  {
    slug: 'drop-zone',
    name: 'Drop Zone',
    type: 'BOOST',
    description: 'Take a free drop within one club length of any spot on the hole, no closer to hole, no penalty.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Better lie ahead.',
    },
  },
  {
    slug: 'the-re-do',
    name: 'The Re-Do',
    type: 'BOOST',
    description: 'Hit a second tee shot if you don\'t like the first. Pick the better one. No stroke penalty.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Second time\'s the charm.',
    },
  },
  {
    slug: 'brush-it-off',
    name: 'Brush It Off',
    type: 'BOOST',
    description: 'Improve your lie one club length anywhere on this hole, including rough or fairway divots.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Tidy up the lie.',
    },
  },
  {
    slug: 'the-gimme',
    name: 'The Gimme',
    type: 'BOOST',
    description: 'Any putt inside the leather (3 feet) is automatic. Don\'t actually putt them.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'That\'s good.',
    },
  },
  {
    slug: 'the-dropdown',
    name: 'The Dropdown',
    type: 'BOOST',
    description: 'Activate after finding a hazard on a shot. Take a no-penalty drop out of any hazard (water, OB, lateral).',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Get out of jail free.',
    },
  },
  {
    slug: 'pendulum',
    name: 'Pendulum',
    type: 'BOOST',
    description: 'Putt with your eyes closed. If you sink any putt, subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'blind_putt' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Blind putt sunk? Enter -2 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'See no evil.',
    },
  },
  {
    slug: 'beer-bonus',
    name: 'Beer Bonus',
    type: 'BOOST',
    description: 'Subtract 1 for each beer you finish on this hole, max -3.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'beers_finished' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'How many beers did you finish?', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Hydrate aggressively.',
    },
  },
  {
    slug: 'liquid-lunch',
    name: 'Liquid Lunch',
    type: 'BOOST',
    description: 'Take a shot or start/finish your drink at the tee. If you make bogey or better, subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'shot_at_tee_par' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'Shot taken AND par or better? Enter -2 if yes, 0 if no', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Fuel for the fire.',
    },
  },
  {
    slug: 'big-brother',
    name: 'Big Brother',
    type: 'BOOST',
    description: 'Choose a partner. If you score lower than them on this hole, subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'beat_partner' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'player_select', label: 'Select rival partner', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Sibling rivalry.',
    },
  },
  {
    slug: 'twinning',
    name: 'Twinning',
    type: 'BOOST',
    description: 'Choose a partner. If you both score the same, both subtract 1.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'same_score_partner' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'player_select', label: 'Select your twin', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Match made in heaven.',
    },
  },
  {
    slug: 'showdown',
    name: 'Showdown',
    type: 'BOOST',
    description: 'Choose a partner. Outdrive AND beat them on this hole — subtract 2.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'outdrive_and_beat' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'player_select', label: 'Select rival', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Best me if you can.',
    },
  },
  {
    slug: 'caddys-pick',
    name: 'Caddy\'s Pick',
    type: 'BOOST',
    description: 'Have a partner pick the club you must use for your tee shot on your next hole. If you make par or better, subtract 1.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'caddy_pick_par' },
      duration: 1,
      requiresTarget: false,
      input: { type: 'player_select', label: 'Select partner to pick your tee club', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Trust the bagman.',
    },
  },
  {
    slug: 'the-streaker',
    name: 'The Streaker',
    type: 'BOOST',
    description: 'Declare how many consecutive greens-in-regulation you\'ll hit. Hit them all → subtract that number from your gross. Miss one → fails.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'consecutive_gir' },
      duration: -1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'How many consecutive GIR will you hit?', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Dart thrower for days.',
    },
  },
  {
    slug: 'no-three-putts',
    name: 'No Three-Putts',
    type: 'BOOST',
    description: 'Declare a number of consecutive holes (2-9) without three-putting. Success → subtract 1 per hole. One three-putt → fails.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'no_three_putt_streak' },
      duration: -1,
      requiresTarget: false,
      input: { type: 'number_input', label: 'How many holes without three-putting?', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Roll it true.',
    },
  },
  {
    slug: 'birdie-hunter',
    name: 'Birdie Hunter',
    type: 'BOOST',
    description: 'For the next 3 holes, every birdie counts double — subtract an additional 1 per birdie.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'birdie_bonus_3' },
      duration: -1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'On the prowl.',
    },
  },
  {
    slug: 'stayin-alive',
    name: 'Stayin\' Alive',
    type: 'BOOST',
    description: 'Avoid all bogeys for the next 3 holes. Success: subtract 3. One bogey or worse: nothing.',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'bogey_free_3' },
      duration: -1,
      requiresTarget: false,
      input: null,
      restrictions: { excludePar3: false },
      flavorText: 'Don\'t trip.',
    },
  },

  // --- NEW ATTACK CARDS (15) ---

  {
    slug: 'double-or-nothing',
    name: 'Double or Nothing',
    type: 'ATTACK',
    description: 'Pick a player. For the next 3 holes, every SCORE counts double (eagles are -4, birdies are -2, bogeys are +2, double-bogeys are +4)',
    effect: {
      scoring: { mode: 'variable', modifier: null, conditionalKey: 'score_double_3' },
      duration: -1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Gambler, are we?',
    },
  },
  {
    slug: 'three-putt-fee',
    name: 'Three-Putt Fee',
    type: 'ATTACK',
    description: 'If your opponent three-putts this hole, add 1 to their score.',
    effect: {
      scoring: { mode: 'manual', modifier: 1, conditionalKey: 'three_putt' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Pay up.',
    },
  },
  {
    slug: 'snowman',
    name: 'Snowman',
    type: 'ATTACK',
    description: 'If your opponent makes 8 or more on this hole, add an extra 2.',
    effect: {
      scoring: { mode: 'manual', modifier: 2, conditionalKey: 'opponent_eight_plus' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Frosty greetings.',
    },
  },
  {
    slug: 'out-of-bounds',
    name: 'Out of Bounds',
    type: 'ATTACK',
    description: 'If your opponent goes OB or loses a ball on this hole, +1 per occurrence.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'opponent_ob_count' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'number_input', label: 'How many OBs/lost balls? +1 each', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Goodbye, ball.',
    },
  },
  {
    slug: 'lefty-for-a-minute',
    name: 'Lefty for a Minute',
    type: 'ATTACK',
    description: 'Opponent must hit one shot opposite-handed (their choice which shot).',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Try the other side.',
    },
  },
  {
    slug: 'eyes-wide-shut',
    name: 'Eyes Wide Shut',
    type: 'ATTACK',
    description: 'Opponent must take their tee shot with eyes closed. Use a spotter for safety. Stanley Kubrick was killed for what he knew.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Trust the swing.',
    },
  },
  {
    slug: 'no-practice-swings',
    name: 'No Practice Swings',
    type: 'ATTACK',
    description: 'Opponent gets zero practice swings on this hole.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Just send it.',
    },
  },
  {
    slug: 'tee-time-attack',
    name: 'Tee Time',
    type: 'ATTACK',
    description: 'Opponent must wait 60 seconds standing over the ball before every shot this hole.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Take all the time.',
    },
  },
  {
    slug: 'the-heckle',
    name: 'The Heckle',
    type: 'ATTACK',
    description: 'You may talk during opponent\'s swings on this hole. Once per shot.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Mind games.',
    },
  },
  {
    slug: 'distance-denied',
    name: 'Distance Denied',
    type: 'ATTACK',
    description: 'Opponent cannot use rangefinder, GPS, or distance markers on this hole.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Eyeball it.',
    },
  },
  {
    slug: 'sing-it',
    name: 'Sing It',
    type: 'ATTACK',
    description: 'Opponent must hum or sing audibly during every backswing on this hole.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Sing for your supper.',
    },
  },
  {
    slug: 'wood-only',
    name: 'Wood Only',
    type: 'ATTACK',
    description: 'Opponent may only use woods (driver, 3W, 5W) for full swings on this hole. Putter still allowed on green.',
    effect: {
      scoring: { mode: 'behavioral', modifier: null, conditionalKey: null },
      duration: 1,
      requiresTarget: true,
      input: { type: 'player_select', label: 'Select opponent', count: null },
      restrictions: { excludePar3: true },
      flavorText: 'Lumberjack mode.',
    },
  },
  {
    slug: 'the-cursed-club',
    name: 'The Cursed Club',
    type: 'ATTACK',
    description: 'Pick a club, and don tell your opponent which club it is. Each time your opponent uses it on this hole, add 1 to their score.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'cursed_club_uses' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'club_select', label: 'Curse a club', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Bad mojo.',
    },
  },
  {
    slug: 'yipsy-daisy',
    name: 'Yipsy Daisy',
    type: 'ATTACK',
    description: 'Opponent misses any putt inside 5 feet on this hole, add 1 per miss.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'short_putt_misses' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'number_input', label: 'How many missed short putts? +1 each', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'The yips strike.',
    },
  },
  {
    slug: 'the-flop',
    name: 'The Flop',
    type: 'ATTACK',
    description: '+1 for each of opponent\'s shots from the rough on this hole, max +3.',
    effect: {
      scoring: { mode: 'manual', modifier: null, conditionalKey: 'rough_shots' },
      duration: 1,
      requiresTarget: true,
      input: { type: 'number_input', label: 'How many shots from the rough? (max 3)', count: null },
      restrictions: { excludePar3: false },
      flavorText: 'Stay in the short stuff.',
    },
  },
]

async function main() {
  console.log('Seeding powerup cards...\n')

  for (const p of POWERUPS) {
    const powerup = await prisma.powerup.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        type: p.type,
        description: p.description,
        effect: p.effect as Prisma.InputJsonValue,
      },
      create: {
        slug: p.slug,
        name: p.name,
        type: p.type,
        description: p.description,
        effect: p.effect as Prisma.InputJsonValue,
      },
    })
    const icon = p.type === 'BOOST' ? '🟢' : '🔴'
    console.log(`  ${icon} ${powerup.name} (${p.type})`)
  }

  const boosts = POWERUPS.filter((p) => p.type === 'BOOST').length
  const attacks = POWERUPS.filter((p) => p.type === 'ATTACK').length
  console.log(`\nDone. Seeded ${POWERUPS.length} powerups (${boosts} boosts, ${attacks} attacks).`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
