-- Enable Row Level Security on all tables.
-- With RLS enabled and no permissive policies, the "anon" role used by
-- Supabase PostgREST is denied access by default.  The "postgres" role
-- (used by Prisma) and "service_role" (used by the admin client) bypass
-- RLS, so application behaviour is unchanged.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlayerProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tournament" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentRound" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Course" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Hole" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeeOption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HoleYardage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RoundPlayerTee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RoundHoleTee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentPlayer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentGroupMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Score" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Powerup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentPowerup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlayerPowerup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Draft" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DraftPick" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentPhoto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatBan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StandaloneRound" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StandaloneScore" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LeagueRoster" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LeagueRosterMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SeasonScheduleEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SeasonRSVP" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Purchase" ENABLE ROW LEVEL SECURITY;
